# Generated by Django 4.2 on 2023-09-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typeguru', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
