# Generated by Django 4.2 on 2023-09-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typeguru', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typingdata',
            old_name='mode',
            new_name='duration',
        ),
    ]
