# Generated by Django 4.2 on 2023-09-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeguru', '0004_user_date_registered_typingdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
