# Generated by Django 4.2 on 2023-09-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typeguru', '0005_alter_user_date_registered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typingdata',
            old_name='date',
            new_name='timestamp',
        ),
    ]
