version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - '5442:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  django:
    environment:
      - DJANGO_ENV=prod
    build:
      context: .
    container_name: django
    command: /usr/local/bin/gunicorn capstone.wsgi:application --config ./gunicorn_config.py
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - '81:80'
    volumes:
      - /path/to/your/ssl/files:/etc/nginx/ssl
    depends_on:
      - django

volumes:
  postgres_data:
