version: '3'

services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/

  nodejs:
    build:
      context: .
      # dockerfile: Dockerfile.nodejs
    container_name: nodejs
    tty: true
    # restart: on-failure
    command: npm run dev
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  django:
    build:
      context: .
      # dockerfile: Dockerfile.python
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  pgdata:
