version: '3'

services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/

  nodejs:
    build:
      context: .
    container_name: nodejs
    tty: true
    command: npm run dev
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  django:
    build:
      context: .
    container_name: django
    command: gunicorn capstone.wsgi:application -b 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    depends_on:
      - db