version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  django:
    build:
      context: .
    container_name: django
    command: /usr/local/bin/gunicorn typeguru.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  postgres_data:
